/**
 * Replace irc nicknames with real names (if available) in W3C minutes
 *
 */

import { type Params, getParams                    } from './params.ts';
import { type FileName, getMinutes, type Nicknames } from "./data.ts";
import { convert, type UserNick                    } from "./nick_convert.ts";

// type Nicknames = Record<string,string> ;

// special lines:

const Specials: RegExp[] = [
    /(<dt>Present<\/dt><dd>)(.*)(<\/dd>)/,
    /(<dt>Chair<\/dt><dd>)(.*)(<\/dd>)/,
    /(<dt>Regrets<\/dt><dd>)(.*)(<\/dd>)/,
    /(<dt>Scribe<\/dt><dd>)(.*)(<\/dd>)/
]

/**
 * Modify one minute file: extract the nicknames, and change them to their full name.
 *
 * Nicknames are extracted:
 *
 * - from the header (present, chair, scribe)
 * - from the content, looking at the `<cite>` element
 *
 * as generated by the scribe tool of W3C.
 *
 * @param input - Input file name
 * @param nicknames - Nick mappings to real names
 * @param out - Output file name. If empty, input file name is reused
 */
async function oneFile(input: FileName, nicknames: Record<string, string>, out: FileName = ""): Promise<void> {
    // Special lines creates a particular problem: nicknames may be repeated and
    // partially overlap in the content.
    const handleOneSpecialLine = (line: string): string => {
        for (const regex of Specials) {
            const regex_result = line.match(regex);
            if (regex_result !== null) {
                const partList: string[] = regex_result[2].split(",")
                    .map((n: string): string => n.trim())
                    .map((n: string): string => n.endsWith('_') ? n.slice(0, n.length - 1) : n)
                    .map((n: string): string => n.toLowerCase())
                    .map((n: string): string => {
                        const realName = nicknames[n];
                        return realName !== undefined ? realName : n;
                    })
                    .filter((n: string): boolean => n !== "");
                return regex_result[1] + [...new Set(partList)].join(", ") + regex_result[3];
            }
        }
        // If we get here, then no special treatment was needed
        return line;
    }

    // Collect the nicknames used in the minutes
    const getNicks = (content: string[]): string[] => {
        const nicks: string[] = [];
        for( const line of content) {
            // action to be taken for each line of the minutes
            // handle the real minutes
            const regex_result = line.match(/<cite>(.*)<\/cite>/);
            if (regex_result !== null) {
                nicks.push(regex_result[1]);
            }
        }

        // Time for some cleanups on the nicknames...
        const final_nicks = nicks
            .map((nick: string): string => {
                nick = nick.toLowerCase();
                if (nick.startsWith('&lt;')) {
                    // these are lines not produced by the scribe
                    nick = nick.substring(4, nick.length - 4);
                }
                if (nick.endsWith(':')) {
                    // the scribe puts this sign there
                    nick = nick.substring(0, nick.length - 1);
                }
                if (nick.endsWith("_")) {
                    // the irc log adds an underscore to the nickname time-to-time
                    nick = nick.substring(0, nick.length - 1);
                }
                return nick;
            })
            // remove empty nicknames, as well the entries of zakim
            .filter((input: string): boolean => input !== "" && input !== "zakim");

        // Remove duplicates
        return [...new Set(final_nicks)];
    };


    const output: string = out || input;
    // console.log(`Handling ${input}, stored in ${output}`);

    const originals: string[] = (await Deno.readTextFile(input)).split('\n');

    // Special lines creates a particular problem: nicknames may be repeated and
    // partially overlap in the content. These must be handled separately; luckily, there are only a few
    // of them. They are handled first:
    const content: string[] = originals.map(handleOneSpecialLine);

    // Get all the nicknames in the text, and concentrate on those that have an associated real name
    const nicks: string[] = getNicks(content).filter((nick: string): boolean => nicknames[nick] !== undefined);

    // Systematically change the first occurrence of nicknames with the real names
    const newContent = content.map((line: string): string => {
        // Filter out the entries generated by zakim
        if (line.match("<cite>&lt;Zakim&gt;</cite>") !== null) {
            return "";
        }

        // if this is a special line, it is considered as handled already; it should
        // be avoid for fear of duplicating names (e.g., when one uses his/her name as nickname)
        for (const regex of Specials) {
            const regex_result = line.match(regex);
            if (regex_result !== null) return line;
        }

        // This somewhat convoluted way of handling is necessary to handle lower/upper case issues
        const one_nick = (current: string, nick: string, replacement: string): string => {
            const regex = new RegExp(`${nick}`,'i');
            return current.replace(regex, `${replacement}`);
        }

        // The same match is done twice; the nicknames may include a '_' character at the end, an artefact of IRC
        for (const nick of nicks) {
            const replacement = nicknames[nick];
            line = one_nick(line, nick, replacement);
            line = one_nick(line, `${nick}_`, replacement);
        }

        return line;
    }).filter((line: string):boolean => line !== "");

    // write the result into the output
    await Deno.writeTextFile(output, newContent.join('\n'));
}

/* ============================================================================================================= */

/**
 * Runner on update minutes' function on all files in parallel
 */
export async function handle_nicknames(): Promise<void> {
    const params: Params = await getParams();
    if (!params.nicknames) {
        console.error("No nickname mapping file has been provided.")
    } else {
        // Get hold of the nicknames. If the input file is user friendly, that must be
        // converted first.
        const nicknames: Nicknames = await (async (fname: FileName): Promise<Nicknames> => {
             if (params?.user_friendly === true) {
                const user_nick = JSON.parse(await Deno.readTextFile(fname)) as UserNick[];
                return convert(user_nick);
            } else {
                return JSON.parse(await Deno.readTextFile(fname)) as Nicknames;
            }
        })(params.nicknames);
        const minutes: FileName[] = await getMinutes(params.directory);

        const minutesPromises: Promise<void>[] = minutes.map((minute: FileName) => oneFile(minute, nicknames));
        // const minutesPromises = [oneFile('../minutes/2026-01-29.html', nicknames, '../minutes/2026-01-29.html'.replace("minutes", "test"))]

        // Run the minute handling in parallel. If one fails, be it, we just forget about the file...
        await Promise.allSettled(minutesPromises);
        console.log("Real names generated successfully")
    }
}
